import {
  Calculator,
  Flask,
  Globe,
  Book,
  Laptop,
  Palette,
  Chat,
  Lightbulb,
  Airplane,
  User,
  Gear,
  Toolbox,
  Handshake,
  ChartLine,
  Database,
  GitBranch,
  ShareNetwork,
  QuestionMark,
  Hammer,
  Camera,
  UsersThree,
  CaretUpDown,
  Icon,
} from "@phosphor-icons/react";

type IconItem = {
  Icon: Icon;
  isSelected: boolean;
};

export const IconsData: IconItem[] = [
  { Icon: Flask, isSelected: true },
  { Icon: Calculator, isSelected: false },
  { Icon: Globe, isSelected: false },
  { Icon: Book, isSelected: false },
  { Icon: Laptop, isSelected: false },
  { Icon: Palette, isSelected: false },
  { Icon: Chat, isSelected: false },
  { Icon: Hammer, isSelected: false },
  { Icon: Database, isSelected: false },
  { Icon: CaretUpDown, isSelected: false },
  { Icon: Camera, isSelected: false },
  { Icon: UsersThree, isSelected: false },
  { Icon: ShareNetwork, isSelected: false },
  { Icon: Lightbulb, isSelected: false },
  { Icon: Airplane, isSelected: false },
  { Icon: User, isSelected: false },
  { Icon: Gear, isSelected: false },
  { Icon: QuestionMark, isSelected: false },
  { Icon: GitBranch, isSelected: false },
  { Icon: Toolbox, isSelected: false },
  { Icon: Handshake, isSelected: false },
  { Icon: ChartLine, isSelected: false },
];
